DEVICE          : 'cuda'
SAVE_DIR        : 'output'

MODEL:
  NAME          : 'MMSegmentor'
  MHA           : False
  PRETRAINED    : True
  ACTIVATION    : 'softmax'
  DECOMPOSITION : 'PCA'

TRAIN:
  IMAGE_SIZE    : [ 1024, 1024 ]
  BATCH_SIZE    : 3
  EPOCHS        : 100
  RESUME        : False
  CHECKPOINT    : ''
  AUX           : False

EVAL:
  MODEL_PATH    : 'output/DeepLabV3_ResNet101_I_model_best.pth'
  IMAGE_SIZE    : [1024, 1024]
  BATCH_SIZE    : 3

LOSS:
  NAME          : 'CrossEntropy'

OPTIMIZER:
  NAME          : 'AdamW'  # or SGD
  LR            : 0.00007
  WEIGHT_DECAY  : 0.01
